### ISSUE TITLE
Intent of Application by Ashana Sharan

### ISSUE THREAD

**Issue by Ashana700** [pgRouting/GSoC-pgRouting#191]
- [ ] Intent of application 
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [ ] Get familiar with C++
- [ ] Get familiar with pgRouting

**Comment by Ashana700** [comment]
Link of issue - [link](https://github.com/Ashana700/GSoC-pgRouting/issues/1)
Link of PR - [link](https://github.com/pgRouting/GSoC-pgRouting/pull/190)

**Comment by Ashana700** [comment]
### **TASK-3 (BUILD LOCALLY PGROUTING)**

[Link of the task 3](https://github.com/Ashana700/GSoC-pgRouting/issues/2#issue-1100699492)

**Comment by krashish8** [comment]
Did not apply
