### ISSUE TITLE
Intent of Application of Manas SIvakumar

### ISSUE THREAD

**Issue by Manas23601** [pgRouting/GSoC-pgRouting#194]
- [ ] Intent of application 
- [ ] Experience with GitHub & Git
- [ ] Build locally pgRouting
- [ ] Get familiar with C++
- [ ] Get familiar with pgRouting

**Comment by Manas23601** [comment]
### Task 1
My name is Manas. I'm a Junior undergraduate at IIITDM K pursuing Computer Engineering. My interests are in Distributed systems and cloud computing. I'm a self motivated person always ready to explore something new everyday. I have a good grasp on C++, python and Git and graph based algorithms. I would like to contribute to PgRouting :)

**Comment by Manas23601** [comment]
### Task 2
Pull request : https://github.com/pgRouting/GSoC-pgRouting/pull/196
Issue Link: https://github.com/Manas23601/GSoC-pgRouting/issues/1

**Comment by Manas23601** [comment]
### Task 3
https://github.com/Manas23601/GSoC-pgRouting/issues/2

**Comment by veenits123** [comment]
In Task 2, add the log of commands in your issue.

**Comment by Manas23601** [comment]
### Task 4
https://github.com/Manas23601/GSoC-pgRouting/issues/3

**Comment by Manas23601** [comment]
### Task 5
https://github.com/Manas23601/GSoC-pgRouting/issues/4

**Comment by krashish8** [comment]
In Task 5, you also need to paste the screenshots of your work (4th point)

**Comment by krashish8** [comment]
Provisionally reviewed, so that you can start getting familiar with pgRouting or work on your [GSoC idea](https://github.com/pgRouting/pgrouting/wiki/GSoC-Ideas:-2022).
As always, we would make a final review when we evaluate the proposals.

**Comment by Manas23601** [comment]
alright, thank you
