### ISSUE TITLE
Intent of application - Xiaochuan Ye

### ISSUE THREAD

**Issue by XueSongTap** [pgRouting/GSoC-pgRouting#276]
- [x] Intent of application 
- [x] Code of Conduct reproduction
- [ ] Experience with GitHub & Git
- [ ] Build locally pgRouting
- [ ] Get familiar with C++
- [ ] Get familiar with pgRouting

# Intent of Application:
- [ ] Write a paragraph about yourself in a comment of this issue.
- [ ] Handwrite a copy the [code of conduct](https://github.com/pgRouting/pgrouting/blob/main/CODE_OF_CONDUCT.md)
  - [ ] Take a picture of copy and upload on a comment of this issue.

**Comment by XueSongTap** [comment]
### Task 1: Intent of application
Hello pgRouting community, my name is Xiochuan Ye and I'm a I am a Master's student from Wuhan University, China. My major is Cartography and Geographical information engineering，I main focus on spatial data computing and I have been familiar with postgis for a while. 
I'm familiar with modern c++ and looking forward to collaborate with the community and  contribute my skills and knowledge to pgRouting project.

**Comment by XueSongTap** [comment]
### Code of Conduct Reproduction
![photo_2023-03-22_23-53-30](https://user-images.githubusercontent.com/46843496/226963482-36de4ec2-8386-41ed-8ce0-be0c47e3f270.jpg)
![photo_2023-03-22_23-53-29](https://user-images.githubusercontent.com/46843496/226963483-a6d86e82-0167-4804-9a55-73904b7535ee.jpg)
![photo_2023-03-22_23-53-28](https://user-images.githubusercontent.com/46843496/226963484-145a94e9-befb-4e7f-8c64-4c933d945299.jpg)
![photo_2023-03-22_23-53-27](https://user-images.githubusercontent.com/46843496/226963490-7f6135ae-6fb8-4185-9337-7430d0e317cc.jpg)
![photo_2023-03-22_23-53-25](https://user-images.githubusercontent.com/46843496/226963507-bc133657-5fe0-4aa6-8118-18026471109d.jpg)
