### ISSUE TITLE
Intent of Application - Dhruv Mehta

### ISSUE THREAD

**Issue by dhruvmehtaaa** [pgRouting/GSoC-pgRouting#363]
- [x] Intent of application 
- [x] Code of Conduct reproduction
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [ ] Get familiar with C++
- [x] Get familiar with pgRouting

# Intent of Application:
- [x] Write a paragraph about yourself in a comment of this issue.
- [x] Handwrite a copy the [code of conduct](https://github.com/pgRouting/pgrouting/blob/main/CODE_OF_CONDUCT.md)
  - [x] Take a picture of copy and upload on a comment of this issue.

**Comment by dhruvmehtaaa** [comment]
# Task 2: Experience with GitHub & Git
[Task 2 Link](https://github.com/dhruvmehtaaa/GSoC-pgRouting/issues/1)

[PR Link](https://github.com/pgRouting/GSoC-pgRouting/pull/368)

**Comment by dhruvmehtaaa** [comment]
# Task 3: Build locally pgRouting

[Task 3 Link](https://github.com/dhruvmehtaaa/GSoC-pgRouting/issues/2)

**Comment by dhruvmehtaaa** [comment]
# Task 4: Get familiar with C++

**Comment by dhruvmehtaaa** [comment]
# Task 5: Get familiar with pgRouting 

[Task 5 Link](https://github.com/dhruvmehtaaa/GSoC-pgRouting/issues/4)

**Comment by dhruvmehtaaa** [comment]
Applying to ZOO-Project this year, hence will close this issue
