### ISSUE TITLE
Intent of Application - Arun Thakur

### ISSUE THREAD

**Issue by bedupako12mas** [pgRouting/GSoC-pgRouting#369]
- [x] Intent of application 
- [x] Code of Conduct reproduction
- [x] Experience with GitHub & Git
- [x] Build locally pgRouting
- [x] Get familiar with C++
- [x] Get familiar with pgRouting

# Intent of Application:
- [x] Write a paragraph about yourself in a comment of this issue.
- [x] Handwrite a copy the [code of conduct](https://github.com/pgRouting/pgrouting/blob/main/CODE_OF_CONDUCT.md)
  - [x] Take a picture of copy and upload on a comment of this issue.

**Comment by bedupako12mas** [comment]
# Task 0: Introduction
Greetings, pgRouting community! I am grateful for the opportunity of becoming a part of this community and interacting with the members and learning together. I am Arun Thakur, a 2023 graduate from IIT Roorkee with a bachelors in Metallurgical and Materials Engineering with a minor in Mathematics. I have decent skills in C++ and python due to the projects I built during my undergraduate degree.
I developed an interest in C++ programming through algorithmic programming contests which I started as a hobby after graduation as I was recovering from a knee surgery([My codeforces profile](https://codeforces.com/profile/bedupako)). My interest in C++ development and algorithms in general was further solidified when I learnt and read about how std::unordered_map can be blown up to have an O(n<sup>2</sup>) time complexity when the inputs are carefully engineered due to the way it is implemented and how to defend against such edge cases to reduce potential collisions. I am very eager to discuss and learn more about C++ developement and Algorithms in general.

**Comment by bedupako12mas** [comment]
# Task 1: Handwrite a copy of the OSGeo Code of Conduct
<details>
<summary>
Click here to view the handwritten pages
</summary>
![page1](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/9f81287b-ca36-4f71-a382-ce5f6fff5405)
![page2](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/77db8116-1c7a-4eae-b589-4010ffeb90b1)
![page3](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/0399c059-0945-420c-bb28-78bda0ae0741)
![page 4](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/f975c3bf-88f1-4c30-a0bd-b3910e124684)
</details>

**Comment by bedupako12mas** [comment]
# Task 2: Experience with Git and GitHub
Work in progress...

**Comment by bedupako12mas** [comment]
# Task 2: Experience with Git and Github
Work in progress

**Comment by bedupako12mas** [comment]
# Task 1: Handwritten copy of Code of Conduct
<details><summary>Click here to view the pages</summary>

![page1](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/582e02ba-b1a9-46ef-abb0-2d9cc367d5d2)

![page2](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/a672aa78-066d-465d-8ac9-45bb36597cc2)

![page3](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/b0683fe2-a0af-4a85-9fe9-c9f92e10e32c)

![page 4](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/28843347-1ad7-472e-8eb4-576bc1d01cff)


</details>

**Comment by bedupako12mas** [comment]
# Task 1: Handwritten copy of Code of Conduct
<details><summary>Click here to view the pages</summary>

![page1](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/582e02ba-b1a9-46ef-abb0-2d9cc367d5d2)

![page2](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/a672aa78-066d-465d-8ac9-45bb36597cc2)

![page3](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/b0683fe2-a0af-4a85-9fe9-c9f92e10e32c)

![page 4](https://github.com/pgRouting/GSoC-pgRouting/assets/141558656/28843347-1ad7-472e-8eb4-576bc1d01cff)


</details>

**Comment by bedupako12mas** [comment]
# Task 2: Experience with Git and Github
Work in Progress...

**Comment by bedupako12mas** [comment]
# Task 3: Build locally pgRouting

**Comment by bedupako12mas** [comment]
# Task 3: Build locally pgRouting
Work in Progress

**Comment by bedupako12mas** [comment]
# Task 3: Build locally pgRouting
work in progress

**Comment by bedupako12mas** [comment]
# Task 4: Get familiar with C++
- [ ] https://www.youtube.com/watch?v=eidEEmGLQcU
  - [ ] Make Report
- [ ] https://www.youtube.com/watch?v=u5senBJUkPc
  - [ ] Make Report
- [ ] https://www.youtube.com/watch?v=YnWhqhNdYyk
  - [ ] Make Report
- [ ] https://www.youtube.com/watch?v=1OEu9C51K2A
  - [ ] Make Report
- [ ] https://www.youtube.com/watch?v=xnqTKD8uD64
  - [ ] Make Report
- [ ] https://www.youtube.com/watch?v=86xWVb4XIyE
  - [ ] Make Report
- [ ] Put the link of this issue on a comment of the issue of task 1

**Comment by bedupako12mas** [comment]
# Task 5: Get familiar with pgRouting
[Link to issue](https://github.com/bedupako12mas/GSoC-pgRouting/issues/4)

**Comment by cvvergara** [comment]
Please dont forget to post here a link to your proposal for feedback

**Comment by bedupako12mas** [comment]
https://docs.google.com/document/d/1RAfzWgrFpuutzdVKyVAwk3D_xIdlG5MhGh0vdNkWTiQ/edit
Thank you for the opportunity, a review and and any feedback would be greatly appreciated
